name: Supabase Ping

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase project (GET request to REST API root)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -sSf -X GET "${SUPABASE_URL}/rest/v1/" \
            -H "apikey: ${SUPABASE_ANON_KEY}" || exit 1

          echo "Supabase project pinged successfully by accessing REST API root."
